- name: Register the current Go version (if any)
  command: /usr/local/go/bin/go version
  ignore_errors: yes
  register: go_version_check
  changed_when: false

- name: Download Go tarball
  get_url:
    url: "{{ go_tarball_location }}"
    dest: "/usr/local/{{ go_tarball }}"
  when: go_version_check is failed or go_version not in go_version_check.stdout
  become: yes

- name: Remove old Go
  file:
    path: /usr/local/go
    state: absent
  when: go_version_check is failed or go_version not in go_version_check.stdout
  become: yes

- name: Extract the go tarball
  unarchive:
    src: "/usr/local/{{ go_tarball }}"
    dest: /usr/local
  when: go_version_check is failed or go_version not in go_version_check.stdout
  become: yes

- name: Remove tarball
  file:
    path: "/usr/local/{{ go_tarball }}"
    state: absent
  become: yes
