[character]
error_symbol = "✗"

[cmd_duration]
min_time = 10
show_milliseconds = true
format = "took [$duration](bold yellow)"

[git_branch]
symbol = "🌱 "

[gcloud]
disabled = true

[memory_usage]
disabled = false
format = "RAM: [$ram_pct](dimmed white) "
threshold = -1
symbol = ""

[time]
disabled = false
format = "[| $time |](yellow) "
time_format = "%T"
utc_time_offset = "+9"
