- name: Register the current Node.js version (if any)
  command: node version
  ignore_errors: yes
  register: node_version_check
  changed_when: false


- name: Install node
  shell:
    cmd: |
      curl -L https://git.io/n-install | bash -s -- -y
    creates: "{{ ansible_env.HOME }}/n"
  when: node_version_check is failed

- name: Install yarn
  environment:
    PATH: "{{ ansible_env.HOME }}/n/bin/:{{ ansible_env.PATH }}"
  npm:
    name: yarn
    global: yes
  when: node_version_check is failed
