[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'srcery-colors/srcery-vim'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'jistr/vim-nerdtree-tabs'

[[plugins]]
repo = 'luochen1990/rainbow'

[[plugins]]
repo = 'reireias/vim-cheatsheet'

[[plugins]]
repo = 'thinca/vim-quickrun'
