[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'srcery-colors/srcery-vim'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'jistr/vim-nerdtree-tabs'

[[plugins]]
repo = 'luochen1990/rainbow'

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
merged = '0'
on_i = 1

[[plugins]]
repo = 'wakatime/vim-wakatime'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tpope/vim-surround'
