- name: Register the current Heroku version (if any)
  command: /usr/local/bin/heroku --version
  register: heroku_version_check
  ignore_errors: yes
  changed_when: false

- block:
  - name: Install installer
    get_url:
      url: https://cli-assets.heroku.com/install.sh
      dest: ./install.sh
      mode: 0755

  - name: Run installer
    shell:
      cmd: sh install.sh
    become: yes

  - name: Remove installer
    file:
      path: ./install.sh
      state: absent
  
  when: heroku_version_check is failed