homebrew_packages:
  - bat
  - curl
  - exa
  - fd
  - fzf
  - ghq
  - go
  - hexyl
  - hyperfine
  - jq
  - mercurial
  - 'n'
  - neovim
  - procs
  - python
  - ripgrep
  - starship
  - tmux
  - tokei
  - wget

homebrew_cask_packages:
  - alacritty
  - discord
  - firefox
  - visual-studio-code
