name: Ansible CI
on:
  push:
  pull_request:
    branches: [ master ]
    types: [ closed ]

jobs:
  build-ubuntu:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
    steps:
    - uses: actions/checkout@v2
    - name: Install Ansible
      run: |
        sudo apt update
        sudo apt install software-properties-common
        sudo apt-add-repository --yes --update ppa:ansible/ansible
        sudo apt install ansible
    - name: Run Ansible Playbook
      run: |
        ansible-playbook main.yml -b

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Ansible
      run: |
        brew install ansible
    - name: Run Ansible Playbook
      run: |
        ansible-playbook main.yml
